config/routes.rb
RebutMe::Application.routes.draw do
  resources :debates

  get "home/index"









  root :to => "debates#index"


end

app/models/debate.rb
class Debate < ActiveRecord::Base
  belongs_to :debate
  has_many :debates, :dependent => :destroy
  
  def display_class
    if is_supporting == true
      return "supporting"
    elsif is_supporting == false
      return "refuting"
    else
      return "blank"
    end
  end

  def support_count
    count = debates.inject(0) {|result, child| result + child.support_count}
    if is_supporting == true
      return count + 1
    elsif is_supporting == false
      return count - 1
    end
    return count
  end

  def subtree_count
    return debates.inject(0) {|result, child| result + child.subtree_count} + debates.count
  end

  def bg_color
    r = 255
    g = 255
    b = 255
    if subtree_count != 0
      if support_count > 0
        r = (subtree_count - support_count) * 255 / subtree_count
      else
        b = (subtree_count + support_count) * 255 / subtree_count
      end
    end
    "rgb(" + r.to_s + ", " + g.to_s + ", " + b.to_s + ")"
  end

  def generate_style
    ('style="background-color:' + bg_color + ';"').html_safe
  end
  
  def supporting_points
    debates.find_all{|debate| debate.is_supporting == true}
  end
  
  def contesting_points
    debates.find_all{|debate| debate.is_supporting == false}
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  # GET /debates
  # GET /debates.xml
  def index
    @debates = Debate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @debates }
    end
  end

  # GET /debates/1
  # GET /debates/1.xml
  def show
    @debate = Debate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @debate }
    end
  end

  # GET /debates/new
  # GET /debates/new.xml
  def new
    @debate = Debate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @debate }
    end
  end

  # GET /debates/1/edit
  def edit
    @debate = Debate.find(params[:id])
  end

  # POST /debates
  # POST /debates.xml
  def create
    @debate = Debate.new(params[:debate])

    respond_to do |format|
      if @debate.debate == nil
        if @debate.save
      	  format.html { redirect_to(@debate) }
          format.xml  { render :xml => @debate, :status => :created, :location => @debate }
      	else	      
          format.html { render :action => "new" }
	  format.xml  { render :xml => @debate.errors, :status => :unprocessable_entity }
 	end
      else
        if @debate.save
	  format.html { redirect_to(@debate.debate) }
	else
	  format.html { render :action => "new" }
	end
      end
    end
  end

  # PUT /debates/1
  # PUT /debates/1.xml
  def update
    @debate = Debate.find(params[:id])


    respond_to do |format|
      if @debate.update_attributes(params[:debate])
        format.html { redirect_to(@debate) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @debate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /debates/1
  # DELETE /debates/1.xml
  def destroy
    @debate = Debate.find(params[:id])
    @debate.destroy

    respond_to do |format|
      format.html { redirect_to(debates_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/debates/_form.html.erb
<% new_debate = Debate.new 
   new_debate.proposition = "Start a new debate" %>
<%= form_for new_debate do |f| %>
  <% if new_debate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_debate.errors.count, "error") %> prohibited this debate from being saved:</h2>

      <ul>
      <% new_debate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <table>
      <tr>
	<td>
	  <%= f.text_field :proposition,
	                   :onfocus => "if (this.getValue() === '" + new_debate.proposition + "'){this.clear();}"%><%= f.submit %>
	</td>
      </tr>
    </table>
  </div>
<% end %>

app/views/debates/_parent_chain.html.erb
<div id="parents">
  <% if debate.debate == nil then %>
    <div id="debateHead" class="border" <%= debate.generate_style %> 
	 onmouseover="addBorder(this);this.style.cursor='pointer'"
	 onmouseout="removeBorder(this)"
	 onclick="window.location='<%= url_for(debate_path(debate)) %>'">
      <%= debate.proposition %>
    </div>
  <% else %>
    <%= render :partial => "parent_chain", :locals => { :debate => debate.debate } %>
    <div class="border" <%= debate.generate_style %> 
	 onmouseover="addBorder(this);this.style.cursor='pointer'"
	 onmouseout="removeBorder(this)"
	 onclick="window.location='<%= url_for(debate_path(debate)) %>'">
      <%= debate.content %>
    </div>
  <% end %>
</div>

app/views/debates/_point.html.erb
<td class="border" <%= point.generate_style %> 
    onmouseover="addBorder(this);this.style.cursor='pointer'" 
    onmouseout="removeBorder(this)"
    onclick="window.location='<%= url_for(debate_path(point)) %>'">
  <div class="point">
    <%= point.content %>
  </div>
</td>

app/views/debates/_points.html.erb
<table>
  <tr>
    <% if (direction == :left) then %>
      <%= render :partial => "point", 
                 :collection => points_to_render, 
                 :as => :point %>
      <%= render :partial => "response_form", :locals => { :is_supporting => is_supporting }%>
    <% else %>
      <%= render :partial => "response_form", :locals => { :is_supporting => is_supporting }%>
      <%= render :partial => "point", 
                 :collection => points_to_render.reverse, 
                 :as => :point %>
    <% end %>
  </tr>
</table>

app/views/debates/_response_form.html.erb
<td>
<% new_debate = @debate.debates.build 
   new_debate.content = "Add your opinion..." %>
<%= form_for new_debate do |support_form| %>
  <% if @debate.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@debate.errors.count, "error") %> prohibited this point from being saved:</h2>
    
    <ul>
      <% @debate.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div>
    <%= support_form.text_area :content, 
	                       :cols => 20, 
                               :rows => 10,
                               :onfocus => "if (this.getValue() === '" + new_debate.content + "'){this.clear();}" %>
  </div>
  <%= support_form.hidden_field :is_supporting, :value => is_supporting %>
  <%= support_form.hidden_field :debate_id, :value => @debate.id %>
  <div class="actions">
    <%= support_form.submit "Submit" %>
  </div>
<% end %>
</td>

app/views/debates/edit.html.erb
<h1>Editing debate</h1>

<%= render 'form' %>

<%= link_to 'Show', @debate %> |
<%= link_to 'Back', debates_path %>

app/views/debates/index.html.erb
<div id="wrap">
  <h1>DebateWithMe!</h1>
  <p>
    DebateWithMe is a website that allows you to have tree-like debates with your friends. Unlike traditional debates, 
    each point can have many other points supporting or contesting it, each of which can also have 
    many points supporting or contesting it. Instead of following a linear, back and forth path,
    the debate can flow more like a tree, with with each topic branching off into many new topics.
  </p>
  <p>
    To start debating, choose one of the debates below, or create a new debate.
  </p>
  
  <b>Ongoing debates:</b>
  <table>
    <% @debates.find_all{|debate| debate.debate == nil}.sort_by{|debate| debate.created_at}.reverse.each do |debate| %>
    <tr>
      <td class="border" <%= debate.generate_style %> 
	  onmouseover="addBorder(this);this.style.cursor='pointer'"
	  onmouseout="removeBorder(this)"
	  onclick="window.location='<%= url_for(debate) %>'">
	<%= debate.proposition %>
      </td>
    </tr>
    <% end %>
  </table>

  <br />
  <div id="NewDebateButton"><%= render "form" %></div>
  <script type="text/javascript">
    var new_debate_form_html = document.getElementById("NewDebateButton").innerHTML;
    FB.Event.subscribe('auth.sessionChange', function(response) 
    {
      if (response.session) {
        document.getElementById("NewDebateButton").innerHTML = new_debate_form_html;
      } 
      else 
      {
        document.getElementById("NewDebateButton").innerHTML = "Login to create a debate";
      }
    });
  </script>
</div>

app/views/debates/show.html.erb
<div id="wrap">
  <p id="notice">
    <%= notice %>
  </p>
  <%= render :partial => "debates/parent_chain", :locals => { :debate => @debate } %>
  
  <div id="leafs">
    <div class="left"> 
      <div class="leftPoints">
	<b>&lt;&lt;&lt;--- Supporting Points</b>
	<%= render :partial => "points", 
                   :locals => { :points_to_render => @debate.supporting_points,
                                :is_supporting => true,
                                :direction => :left } %>
      </div>
    </div>
    
    <div class="right">
      <div class="rightPoints">
	<b>Contesting Points ---&gt;&gt;&gt;</b>
	<%= render :partial => "points", 
	           :locals => { :points_to_render => @debate.contesting_points,
	                        :is_supporting => false,
                                :direction => :right} %>
      </div>
    </div>
  </div>
  
  <div id="footer">
    <%= link_to 'Home', debates_path %> |  
    <%= link_to 'Delete', @debate, :method => :delete %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <title>DebateWithMe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p><fb:login-button autologoutlink="true"></fb:login-button></p>
  
<div id="fb-root"></div>

<script src="http://connect.facebook.net/en_US/all.js"></script>

<script>
  FB.init({appId: '241135795910479', status: true, cookie: true, xfbml: true});
</script>

  <%= yield %>
  
</body>
</html>